services:
  - type: web
    name: projet-paludisme
    env: python
    build:
      pythonVersion: 3.10
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 8000
    branch: main
    plan: free
