services:
  - type: web
    name: projet-paludisme
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 8000
    pythonVersion: 3.11.4
    branch: main
    plan: free
